library(datasets)
house <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
test <- subset(house, Date =="1/2/2007"| Date =="2/2/2007")
test$Date <- as.Date(test$Date,"%d/%m/%Y")
test$daytime <- strptime(paste(test$Date,test$Time), "%Y-%m-%d %H:%M:%S")
test$Global_active_power <- as.numeric(test$Global_active_power)
test$Global_reactive_power <- as.numeric(test$Global_reactive_power)
test$Voltage <- as.numeric(test$Voltage)
test$Sub_metering_1 <- as.numeric(test$Sub_metering_1)
test$Sub_metering_2 <- as.numeric(test$Sub_metering_2)
test$Sub_metering_3 <- as.numeric(test$Sub_metering_3)
png("plot4.png")
par(mfrow=c(2,2), mar= c(4,4,2,1), oma=c(0,0,2,0))
plot(test$daytime, test$Global_active_power, type= "l", xlab = "", ylab = "Global Active Power")
plot(test$daytime, test$Voltage, type = "l", xlab = "daytime", ylab = "Voltage")
plot(test$daytime, test$Sub_metering_1,type = "l",xlab = " ", ylab = "Energy Submetering")
  lines(test$daytime, test$Sub_metering_2, col= "red")
  lines(test$daytime, test$Sub_metering_3, col= "blue")
  legend("topright", c("Sub_metering1", "Sub_metering2","Sub_metering3"), cex = 0.4, lty = 1, lwd = 2.5, col = c("black","red","blue"))
plot(test$daytime, test$Global_reactive_power, type = "l", xlab = "daytime", ylab = "Global_reactive_power")
dev.off
